### ISSUE TITLE
CSV File Opens in one column

### ISSUE THREAD

**Issue by gtnarg** [frosch95/SmartCSV.fx#12]
Hi Andreas,

When I attempt to open a csv file it all opens in one column.

The delimiter character is set to "," in preferences.  The csv file is attached.

Thanks,
Grant

![image](https://cloud.githubusercontent.com/assets/1252704/18515776/8747a1d2-7a64-11e6-88d4-cfefafb0279b.png)

[sample.zip](https://github.com/frosch95/SmartCSV.fx/files/472243/sample.zip)

**Comment by frosch95** [comment]
Just loading and saving the preferences is not enough. They should be used in the code as well :-)
Fixed in the master branch, but I am on vacation and have not enough upload bandwith to provide a new zip file. Will do this on monday.
