### ISSUE TITLE
Not correct opening file

### ISSUE THREAD

**Issue by Ygarr** [frosch95/SmartCSV.fx#25]
Compare. PySpread opens correctly
![bug2022-10-02_12-50](https://user-images.githubusercontent.com/14309871/193448204-cc482978-9eef-4ab8-8c46-248b25887d78.png)

Example of file:
[test_write.csv](https://github.com/frosch95/SmartCSV.fx/files/9692155/test_write.csv)

**Comment by frosch95** [comment]
@Ygarr have you set the delimeter char in the settings to semicolon?
And SmartCVS expects a header line. The first line isused as header line.

**Comment by frosch95** [comment]
As I tested the given csv and it worked as expected, I clause the issue.

**Comment by Ygarr** [comment]
Ok
![image](https://user-images.githubusercontent.com/14309871/195917154-d63d4daf-e882-469d-a7ea-5f29eab7ae0f.png)
